### PR TITLE
add BMG scraper

### PR DESCRIPTION
**Pull request by Runinho**
very nice Source from the Bundesamt fuer Gesundheit with 106 question answer pairs.

We have to decide if we want to include:
https://www.zusammengegencorona.de/informieren/wirtschaftliche-folgen/
https://www.zusammengegencorona.de/informieren/weitere-informationen/
these sites answer only very specific questions or link to other sites.

### CODE REVIEW

**Review by Timoeller — CHANGES_REQUESTED** [review]
Awesome. I saw this site this morning, it is a great addition for our German sources.

When I test it it just gives 8 Questions back  - only for site: https://www.zusammengegencorona.de/informieren/informationen-zum-test/

Did you use the latest Scrapy==2.0.1 version to crawl it?

**Comment by Runinho** [comment]
Yes i used Scrapy==2.0.1. But i registered multiple urls.
I used the following code to test the crawler:
```
from scrapy.crawler import CrawlerProcess
from BMG_scraper import CovidScraper
from scrapy.signalmanager import dispatcher
from scrapy import signals
process = CrawlerProcess({
    'USER_AGENT': 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'
})

results = []

def crawler_results(signal, sender, item, response, spider):
    results.append(item)
dispatcher.connect(crawler_results, signal=signals.item_passed)
    
process.crawl(CovidScraper)
process.start()
```

`results` contains than an array with the results for each site.

I suspect this has something todo with how our meta crawler works. Because this Scraper is using multiple urls....

**Comment by Timoeller** [comment]
Ok, this one is on me. I tested it in a wrong way that did not fetch all results. Sooooory : )
This scraper is working like a charm.

Could you adjust the language tag and add country = "DE" to the metadata? Then I can merge it. Thanks @Runinho

**Comment by Runinho** [comment]
perfect. I fixed the language code and country @Timoeller

**Pull request merged**
