### PR TITLE
Add Folkhälsomyndigheten as a source with data in Swedish and English

### PR DESCRIPTION
**Pull request by ViktorAlm**
Here's two new sources from the Swedish government agency for public health. Hopefully I can be more helpful when I get more familiar. I'm very interested in haystack and this is a great project for it. Im very interested in helping with getting this running on the Covid research dataset for healthcare professionals.

https://www.folkhalsomyndigheten.se/the-public-health-agency-of-sweden/communicable-disease-control/covid-19/

https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/fragor-och-svar/

### CODE REVIEW

**Comment by tholor** [comment]
Awesome, thanks for contributing this @ViktorAlm! 

@Timoeller, please review.

**Comment by Timoeller** [comment]
So funny, I had to laugh when I read the PR description. Thanks for integrating this!

@bogdankostic will review this one.

**Review by bogdankostic — CHANGES_REQUESTED** [review]
Thank you for contributing! Looking good, just one minor thing:
Question and category column should be list of strings. Currently it's list of lists of strings.

Do you want to change this yourself or should I do it?

**Comment by ViktorAlm** [comment]
> So funny, I had to laugh when I read the PR description. Thanks for integrating this!
> 
> @bogdankostic will review this one.

Same base language different branches and merges over time makes German and Swedish quite similar. When I had tests in German back in school it was sometimes possible to make up a German sounding word from Swedish and it often turned out to be an actual German word  :). If that was what you found funny.

**Review by bogdankostic — APPROVED** [review]
Looking good! :)

**Pull request merged**
