### PR TITLE
Added Scraper for page from Berliner Senat and IHK

### PR DESCRIPTION
**Pull request by bogdankostic**

### CODE REVIEW

**Review by Timoeller — CHANGES_REQUESTED** [review]
Jummy, more data sources! : )

I have a couple of proposed changes:
1. Can you please name the class "CovidScraper", this is needed for the meta scraper to work. See [here](https://github.com/deepset-ai/COVID-QA/blob/master/data/scrapers/META_scraper.py#L58)

2. could you have pep8 conforming indentation please. See [here](https://www.python.org/dev/peps/pep-0008/#indentation)

3. Another idea I had is to include a list of all questions coming from this scraper into the description of the PR. That way we can quickly check if it is working correctly.

Thanks @bogdankostic

**Comment by bogdankostic** [comment]
I hope the scraper now looks fine to you, @Timoeller ! :)
These are the questions returned by the scraper:

```
0 Wie unterstützt der Berliner Senat Unternehmen und Beschäftigte, um die Folgen der Corona-Pandemie abzumildern?
1 Wie erhalte ich Liquiditätshilfen vom Berliner Senat?
2 Ich bin Soloselbstständige*r oder Kleinunternehmer*in. Welche Hilfen erhalte ich vom Berliner Senat?
3 Wie reagiere ich als Arbeitgeber*in bei einem Verdachtsfall im Unternehmen?
4 Welche Ansprüche auf Entschädigungsleistungen habe ich, wenn ich als Arbeitnehmer*in oder Selbständige*r unter Quarantäne gestellt werde?
5 Haben Beschäftigte einen Anspruch darauf, im Home-Office zu arbeiten?
6 Darf mein Chef mich einfach nach Hause schicken, wenn ich Husten habe?
7 Welche Schulen sind von den Schließungen betroffen?
8 Sind freie Träger von den Schließungen auch betroffen?
9 Woher weiß ich, ob mein Beruf ein „systemrelevanter Beruf“ ist und ich Anspruch auf eine Notfallversorgung für mein Kind habe?
10 An wen wende ich mich, wenn ich eine Notfallversorgung in Anspruch nehmen möchte?
11 Was ist mit Musikschulen?
12 Ich studiere, forsche oder arbeite an einer Berliner Hochschule. Was muss ich nun beachten?
13 Darf ich meine Freund*in/ Angehörige im Krankenhaus oder Pflegeheim besuchen?
14 Ich bekomme ein Kind. Darf mich jemand begleiten und nach der Geburt besuchen?
15 Darf ich mich mit Freunden zu Hause treffen?
16 Gelten die Abstandsregeln auch im Freien?
17 Kann ich noch zum Sport gehen?
18 Sind Spielplätze geöffnet?
19 Sind Veranstaltungen und Versammlungen komplett verboten?
20 Welche Gewerbe haben geschlossen?
21 Wo kann ich noch einkaufen gehen und was hat darüber hinaus noch auf?
22 Müssen wir mit damit rechnen, dass Lebensmittel knapp werden?
23 Was muss ich mit Blick auf die Gerichtsbarkeit in Berlin wissen?
24 Kann ich noch mit den öffentlichen Verkehrsmitteln fahren?
25 Ist der Regionalverkehr eingeschränkt?
26 Welche Länder sind besonders stark von Corona betroffen?
27 Welche Reisebeschränkungen in andere Länder gibt es gegenwärtig?
28 Wie kann ich mich und andere vor Corona schützen?
29 Helfen Masken zum Schutz vor Corona?
30 Kann ich mich vor Corona impfen lassen?
31 Wer sollte sich testen lassen, ob eine Corona-Infektion vorliegt?
32 Was ist das Corona-Virus und was sind die Symptome?

```

**Comment by bogdankostic** [comment]
I just added another scraper for a IHK-page.

```
0 Wo erhalte ich aktuelle Informationen zum Coronavirus?
1 Welche Regeln muss ich mit meinem Unternehmen im Kampf gegen das Coronavirus beachten?
2 Wie kann ich mich über die aktuelle Lage im vom Coronavirus betroffenen Ausland informieren?
3 Wer zahlt den Lohn, wenn meine Mitarbeiter unter Quarantäne gestellt werden?
4 Wie sehen die neuen Kurzarbeitsregelungen der Bundesregierung aus?
5 Welche Erleichterungen gibt es für Unternehmen im Hinblick auf Steuerzahlungen?
6 Wegen der Coronavirus-Krise muss mein Betrieb eine finanzielle Durststrecke überbrücken. Gibt es dafür Unterstützung?
7 Gibt es Unterstützung für die Einrichtung von Heimarbeitsplätzen?
8 Kann ich auch als Selbstständiger wegen einer angeordneten Quarantäne eine Entschädigung erhalten? 
9 Wo kann ich für mein Unternehmen eine Soforthilfe beantragen?
10 Wie reagiere ich bei einem Verdachtsfall im Unternehmen oder bei infizierten Mitarbeitern?
11 Welche Geschäfte dürfen jetzt zu welchen Zeiten öffnen?
12 Wie kann ich Kunden oder Mitarbeiter ohne Deutschkenntnisse schnell informieren?
13 Was kann ich tun, damit meine Beschäftigten trotz Schul- und Kita-Schließungen arbeiten können? 
14 Wie kann der Arbeitsschutz gewährleistet werden?
15 Welche Ausnahmen gelten jetzt für Güterkraftfahrer?
16 Was muss ich beim Eingang internationaler Postpakete beachten?
17 Was kann ich tun, wenn meinem Unternehmen die Lieferanten aus dem Ausland wegbrechen?
18 Was gilt für den Export medizinischer Schutzausrüstung ins Ausland?
19 Wer kommt für Ausfälle auf, wenn ein Auftrag wegen des Coronavirus unter Berufung auf "höhere Gewalt" platzt?
20 Was muss ich bei der Verarbeitung personenbezogener Daten beachten?
21 Kann ich meine Reisepläne umsetzen? Finden Veranstaltungen statt?
22 Wie kann ich als Unternehmen beurteilen, ob ich eine Veranstaltung absagen muss oder nicht?
23 Hat das Coronavirus auch Auswirkungen auf IHK-Prüfungen? Finden die geplanten Termine statt? 
24 Verlängert sich die Ausbildungszeit, wenn die Prüfung verschoben wird?
25 Wann werden verschobene IHK-Prüfungen nachgeholt?
26 Mein Betrieb wurde durch die Behörden geschlossen. Wie soll ich nun ausbilden?
27 Wir haben kaum Aufträge bzw. der Betrieb ist geschlossen. Kann mein Azubi seine Stunden reduzieren?
28 Darf mein Azubi im Homeoffice arbeiten?

```

**Review by Timoeller — APPROVED** [review]
Looking good. Thanks for implementing the changes.

**Pull request merged**
