### PR TITLE
Testing git commits, pull request and adding aggregation done by computer science student

### PR DESCRIPTION
**Pull request by jsquire1**
This was simple test in order to fully understand pushing to GitHub.

### CODE REVIEW

**Comment by Timoeller** [comment]
Hey @jsquire1 do you also know the other people opening PRs in this repository?

If so, could you please explain why there is so much activity for this repo now? :smiley: 

To be honest, it will be very difficult for us to maintain so much activity beside our other ongoing projects...

**Comment by jsquire1** [comment]
Hi Timoeller, yes I am aware of some of the other individuals who are contributing. We are actually Computer Science students at York University, Toronto, Canada and we are tasked with adding Aggregation "has-a" relationship to a list of repositories, this one included.

**Comment by Timoeller** [comment]
Wow, thanks for clarifying. How did we get on that list if I might ask?

We do have a very active project that also deals with QA (and other things search related), there we can support much more if your instructor thinks that is relevant: https://github.com/deepset-ai/haystack

**Comment by jsquire1** [comment]
You are welcome! It was a list our lecturer provided, actually. So we chose from a list of seven Covid open-source projects, and COVID Q/A was included. 
Okay, I will share this information with my lecturer, and I must also thank you for your generous response.

**Comment by Timoeller** [comment]
Ah that means you were interested in QA? Then you really should check out haystack, you should be able to apply QA there on the whole CORD-19 dataset rather easily.
You can also used the pretrained models that we created and uploaded at the huggingface modelhub: https://huggingface.co/deepset/roberta-base-squad2-covid

**Pull request closed without merging**
