### PR TITLE
Added unified endpoint to answer a question

### PR DESCRIPTION
**Pull request by sfakir**
This opens a following todo of routing the question correctly to the right model.

### CODE REVIEW

**Review by tanaysoni — APPROVED** [review]

**Comment by theapache64** [comment]
Is this change deployed? If not, what the estimated deployment time ?

**Comment by tanaysoni** [comment]
Hi @theapache64, the change is deployed now!

**Comment by theapache64** [comment]
@tanaysoni When I use the newly introduced route (`/ask`), How do I add feedback, as I wouldn't know the model id ?

**Comment by tanaysoni** [comment]
@theapache64 this [PR](https://github.com/deepset-ai/COVID-QA/pull/90) (now deployed) adds the `model_id` in the response body.

**Comment by theapache64** [comment]
@tanaysoni Ok. good work brother :+1:

**Pull request merged**
